spring:

  datasource:
    url: jdbc:h2:file:./data/testdb
#    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update
#      dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

